### ISSUE TITLE
How to implement Promise.all() in offlineapi

### ISSUE THREAD

**Issue by thamizh82** [Exilz/react-native-offline-api#12]
Hi,

I am using Promise.all() method for multiple api request.
e.g 
Promise.all(['http://url1.com/api', 'http://url1.com/api2']);
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all

How to implement this functionality in offlineapi.

Thanks in Advance.

**Comment by Exilz** [comment]
Hi,
`api.fetch` returns a promise, so you can use `Promise.all` like you usually would.

```javascript
const data = await Promise.all([
    api.fetch('service1'),
    api.fetch('service2',  { pathParameters: { id: 'example' } }),
    api.fetch('service3', { pathParameters: { _id: 'example' } })
]);
console.log(data); // [result1, result2, result3]...
```

**Comment by thamizh82** [comment]
Thanks for immediate reply.

Will try this.
