### ISSUE TITLE
Fetch both headers at data in the same request

### ISSUE THREAD

**Issue by thamizh82** [Exilz/react-native-offline-api#13]
Hi,

In the fetch method response data not having header status like 200, 400 ...etc
I need both the header status and data in my use-case.
How to get this header status in the response.

Thanks

**Comment by Exilz** [comment]
Unfortunately, you can only fetch the data or the headers at once.
Adding a method that does both might be an interesting feature to add.

**Comment by thamizh82** [comment]
I used rawData: true and fixed the issue.

Thanks

**Comment by Exilz** [comment]
Oh, you're right, I didn't even think about this prop 😄 

Thanks for answering so quick 👍

**Comment by thamizh82** [comment]
:+1:
