### ISSUE TITLE
app is crash when open

### ISSUE THREAD

**Issue by Q8hma** [Exilz/react-native-offline-api#21]
Hello 
my app is crash and close after calling "OPEN database: apipeline.db"

this is log 

```
01-20 08:50:25.864 29083 29120 I ReactNativeJS: 'Setting debug to:', false
01-20 08:50:25.865 29083 29120 I ReactNativeJS: Promise based runtime ready
01-20 08:50:25.866 29083 29120 I ReactNativeJS: OPEN database: apipeline.db
01-20 08:50:25.991 29083 29120 I ReactNativeJS: Running application "000000" with appParams: {"rootTag":1}. __DEV__ === false, development-level warning are OFF, performance optimizations are ON

```

any help ?

thnx

**Comment by Q8hma** [comment]
only in android but ios work fine

**Comment by Exilz** [comment]
Your logs don't say anything about this plugin. What makes you think
apipeline is crashing your app ?
Are you using SQLite ?

Le dim. 20 janv. 2019 à 06:58, HAMAD ADHBIYAH <notifications@github.com> a
écrit :
