### ISSUE TITLE
how to apply global headers?

### ISSUE THREAD

**Issue by AbanoubNassem** [Exilz/react-native-offline-api#27]
currently I can' find a way to apply global `Headers` I have to apply it per service/request , or I'm missing something here?

**Comment by Exilz** [comment]
You should use a middleware : https://github.com/Exilz/apipeline/blob/master/docs/middlewares.md#middlewares

Just use an `async` function that returns an object with your headers.

**Comment by AbanoubNassem** [comment]
well I have taken a different approach ,  I made a custom `fetch` function and passed it to `fetchMethod`

```
fetching = (url: string, options?: any): Promise<any> => {
    return fetch(url, {
      headers: {
        "Content-Type": "application/json",
        "X-Requested-With": "XMLHttpRequest"
      }
    });
  };
```

and it worked perfectly , this will allow me to add dynamic headers later
