### ISSUE TITLE
Fetching any kind of data, not just JSON

### ISSUE THREAD

**Issue by edrichhans** [Exilz/react-native-offline-api#5]
Hi! I'm trying to fetch data that does not return JSON, but rather returns RSS format. It returns an error:

`[Error: SyntaxError: JSON Parse error: Unrecognized token '<']`

Any help / alternative would be nice. Thanks!

**Comment by Exilz** [comment]
Hi,
I didn't think about adding an option to fetch data that's not in JSON. Once the network request is successful, I call `res.data.json()` no matter what.

I should add an option to circumvent that behavior, so you can fetch any kind of data you want whilst keeping the cache layer.

Maybe a `raw` key in the [services options](https://github.com/Exilz/react-native-offline-api#services-options), or something like that ?

**Comment by Exilz** [comment]
Okay, so I added a `rawData` key that you can either use as a service option, or as a fetch option if you need to fetch anything else than JSON data.

So, you can set your service like this : `testRSS: { path: 'mydata.xml', rawData: true }` or directly when calling the fetch method : `await api.fetch('testRSS', { rawData: true })`

I'll soon publish this with some fixes.
